FROM php:7.2-apache

# Install mysql driver
RUN apt-get update \
  && echo 'deb http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list \
  && echo 'deb-src http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list \
  && apt-get install -y gnupg wget \
  && wget https://www.dotdeb.org/dotdeb.gpg -O /tmp/dotdeb.gpg \
  && apt-key add /tmp/dotdeb.gpg \
  && apt-get update


RUN docker-php-ext-install pdo_mysql \
  && touch /usr/local/etc/php/conf.d/php.ini \
    && echo "upload_max_filesize = 5G" >> /usr/local/etc/php/conf.d/php.ini \
    && echo "post_max_size = 5G" >> /usr/local/etc/php/conf.d/php.ini


RUN apt-get install -y zlib1g-dev libpng-dev

RUN docker-php-ext-install zip
RUN docker-php-ext-install gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get -y install supervisor

# Enable mod_rewrite
RUN a2enmod rewrite
